### ISSUE TITLE
Blank screen with console errors

### ISSUE THREAD

**Issue by jlarmstrongiv** [ozkanonur/nestjs-enlighten#12]
Hi 👋 I was trying to test out this package, but I ran into these console errors:

![image](https://user-images.githubusercontent.com/20903247/91039164-09e73500-e5da-11ea-9e4e-deab57a72a6c.png)

I copied and pasted from the readme, ran `npm run start:dev`, and added `throw new Error('sanity')` in my code.  I’m running `"@nestjs/common": "^7.0.0",` and `"nestjs-enlighten": "0.0.5-beta"`.

I really like the idea though, would love to see it working 😄 maybe I missed a step or something

**Comment by jlarmstrongiv** [comment]
I also received an automated email stating:

```
Run failed for master (e4d22fb)

Repository: ozkanonur/nestjs-enlighten
Workflow: 
Duration: 0.0 seconds
Finished: 2020-08-24 11:21:06 UTC

View results

Jobs:
```

**Comment by onur-ozkan** [comment]
> Hi  I was trying to test out this package, but I ran into these console errors:
> 
> ![image](https://user-images.githubusercontent.com/20903247/91039164-09e73500-e5da-11ea-9e4e-deab57a72a6c.png)
> 
> I copied and pasted from the readme, ran `npm run start:dev`, and added `throw new Error('sanity')` in my code. I’m running `"@nestjs/common": "^7.0.0",` and `"nestjs-enlighten": "0.0.5-beta"`.
> 
> I really like the idea though, would love to see it working  maybe I missed a step or something

Thanks for the good thoughts! Can you share the repository where you are trying to use this package? I tried this package with Nest 6.7 and could not see this error.

**Comment by jlarmstrongiv** [comment]
Thanks for getting back to me!  I tried with a new project, and it worked.  I then tried with my existing project where I originally saw the error, and it worked.  I guess I’ll close this issue since I can no longer reproduce the error
