### ISSUE TITLE
npm install does not install dist directory

### ISSUE THREAD

**Issue by danielkbx** [ozkanonur/nestjs-enlighten#17]
When installing 0.0.7-beta, the ```dist``` folder is missing in the package. Therefore, the module does not work.
When installing the previous version (```npm install nestjs-enlighten@0.0.6-beta```), everything is fine.

Probably, there is something wrong with the build process.

I hope, I did not break something with my PR from yesterday.

**Comment by onur-ozkan** [comment]
Probably I forgot to build lib before I publish it. I will fix it today.
